coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 100%
      fepack-image:
        target: 100%
        threshold: 100%

comment:
  layout: "header, reach, diff, flags, components"

component_management:
  individual_components:
    - component_id: fepack-image
      name: "@fepack/image"
      paths:
        - packages/image
