name: Bug Report
description: Report a reproducible bug or regression in fepack.
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: "Description of the Issue"
      description: "Please provide a detailed description of the problem. If possible, elaborate on when and how the issue arises."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Expected Behavior"
      description: "Describe what you expected to happen if the issue hadn't occurred."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Screenshots"
      description: "Attach any screenshots that might help in understanding the issue."

  - type: textarea
    attributes:
      label: "Proposed Solution"
      description: "If you have any suggestions on how the problem can be resolved, please provide them."
