name: Feature Request
description: Use this to suggest a new feature or an improvement to an existing feature in fepack.
title: "feat: "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: "Feature Description"
      description: "Please provide a detailed description of the feature you would like to add or improve."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Additional Information"
      description: "Include any additional information relevant to the feature request."
