---
name: "Feature Request"
about: Suggest a new feature or an enhancement to an existing one.
title: "feat: "
labels: "enhancement"
---

<!--
Please provide a succinct and clear description of the proposed feature or enhancement.
Describe in detail what you want to suggest and why it's important.
-->

## Feature Description:

<!--
Clearly and concisely describe the feature you'd like to see added or improved upon.
-->


## Additional Information:

<!--
If there's any other context, details, or information related to this feature request,
please provide it here.
-->
