name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "packages/**"

jobs:
  quality:
    name: Check quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: ["pnpm lint, pnpm test, pnpm type:check"]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.5.1
